CREATE DATABASE `SJLeeBlogs` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE Article (
  ATID int(11) NOT NULL AUTO_INCREMENT,
  ATType int(11) NOT NULL DEFAULT '0' COMMENT '文章分类ID（1生活日记/2工作心得/3关于我）',
  ATTitle varchar(200) NOT NULL DEFAULT '',
  ATContent varchar(20000) NOT NULL DEFAULT '' COMMENT '文章内容',
  ATCommentCount int(11) NOT NULL DEFAULT '0' COMMENT '评论数',
  ATAddTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATModifyTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATRowStatus int(11) NOT NULL DEFAULT '1' COMMENT '1有效0删除',
  PRIMARY KEY (`ATID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文章信息';

CREATE TABLE ArticleComments (
  ACID int(11) NOT NULL AUTO_INCREMENT,
  ACType int(11) NOT NULL DEFAULT '0' COMMENT '文章分类ID（1生活日记/2工作心得）',
  ACATID int(11) NOT NULL DEFAULT '0' COMMENT '文章表ID',
  ACParentID int(11) NOT NULL DEFAULT '0' COMMENT '评论的ACID',
  ACCommenter varchar(100) NOT NULL DEFAULT '' COMMENT '评论人昵称',
  ACIPAddress varchar(50) NOT NULL DEFAULT '' COMMENT 'IP地址',
  ACComments varchar(2000) NOT NULL DEFAULT '' COMMENT '评论内容',
  ACAddTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  ACModifyTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  ACRowStatus int(11) NOT NULL DEFAULT '1' COMMENT '1有效0删除',
  PRIMARY KEY (`ACID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文章评论';

CREATE TABLE GuestMessages (
  GMID int(11) NOT NULL AUTO_INCREMENT,
  GMParentID int(11) NOT NULL DEFAULT '0' COMMENT '评论的GMID',
  GMGuestName varchar(100) NOT NULL DEFAULT '' COMMENT '访客昵称',
  GMIPAddress varchar(50) NOT NULL DEFAULT '' COMMENT 'IP地址',
  GMMessages varchar(2000) NOT NULL DEFAULT '' COMMENT '留言内容',
  GMAddTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  GMModifyTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  GMRowStatus int(11) NOT NULL DEFAULT '1' COMMENT '1有效0删除',
  PRIMARY KEY (`GMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='留言表';

CREATE TABLE Logs (
  LGID int(11) NOT NULL AUTO_INCREMENT,
  LGType int(11) NOT NULL DEFAULT '0' COMMENT '操作类型（1生活日记/2工作心得/3关于我/4评论）',
  LGOPType int(11) NOT NULL DEFAULT '1' COMMENT '操作类型（1修改/0删除）',
  LGFKey int(11) NOT NULL DEFAULT '0' COMMENT '外键ID',
  LGOPUser varchar(100) NOT NULL DEFAULT '',
  LGOPTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LGID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='操作日志';

CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(20) NOT NULL DEFAULT '',
  email varchar(80) NOT NULL DEFAULT '',
  `password` varchar(50) NOT NULL DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  roletype int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;